let stockProductos = [
    {id: 1, nombre: "Buzo Pikachu", tipo: "buzo", cantidad: 1, desc: "Buzo de la mascota de la compañia", precio: 1200, talle: "L", img: './img/buzo.jpg'},
    {id: 2, nombre: "Buzo Pikachu", tipo: "buzo", cantidad: 1, desc: "Buzo de la mascota de la compañia", precio: 1100, talle: "L", img: './img/buzo.jpg'},
    {id: 3, nombre: "Buzo Pikachu", tipo: "buzo", cantidad: 1, desc: "Buzo de la mascota de la compañia", precio: 1200, talle: "M", img: './img/buzo.jpg'},
    {id: 4, nombre: "Buzo Pikachu", tipo: "buzo", cantidad: 1, desc: "Buzo de la mascota de la compañia", precio: 1400, talle: "M", img: './img/buzo.jpg'},
    {id: 5, nombre: "Buzo Pikachu", tipo: "buzo", cantidad: 1, desc: "Buzo de la mascota de la compañia", precio: 1200, talle: "S", img: './img/buzo.jpg'},
    {id: 6, nombre: "Buzo Pikachu", tipo: "buzo", cantidad: 1, desc: "Buzo de la mascota de la compañia", precio: 1500, talle: "S", img: './img/buzo.jpg'},
    {id: 7, nombre: "Remera iniciales", tipo: "remera", cantidad: 1, desc: "Los 3 iniciales de Kanto + Pikachu", precio: 500, talle: "L", img: './img/remera.jpg'},
    {id: 8, nombre: "Remera iniciales", tipo: "remera", cantidad: 1, desc: "Los 3 iniciales de Kanto + Pikachu", precio: 500, talle: "L", img: './img/remera.jpg'},
    {id: 9, nombre: "Remera iniciales", tipo: "remera", cantidad: 1, desc: "Los 3 iniciales de Kanto + Pikachu", precio: 500, talle: "M", img: './img/remera.jpg'},
    {id: 10, nombre: "Remera iniciales", tipo: "remera", cantidad: 1, desc: "Los 3 iniciales de kanto + Pikachu", precio: 700, talle: "M", img: './img/remera.jpg'},
    {id: 11, nombre: "Remera iniciales", tipo: "remera", cantidad: 1, desc: "Los 3 iniciales de kanto + Pikachu", precio: 700, talle: "S", img: './img/remera.jpg'},
    {id: 12, nombre: "Remera iniciales", tipo: "remera", cantidad: 1, desc: "Los 3 iniciales de kanto + Pikachu", precio: 700, talle: "S", img: './img/remera.jpg'},
    {id: 13, nombre: "Camisa de Pueblo Lavanda", tipo: "camisa", cantidad: 1, desc: "Los fantasmas mas queridos, Gastly ,Haunter y Gengar", precio: 900, talle: "L", img: './img/camisa.jpg'},
    {id: 14, nombre: "Camisa de Pueblo Lavanda", tipo: "camisa", cantidad: 1, desc: "Los fantasmas mas queridos, Gastly ,Haunter y Gengar", precio: 1400, talle: "S", img: './img/camisa.jpg'},
    {id: 15, nombre: "Camisa de Pueblo Lavanda", tipo: "camisa", cantidad: 1, desc: "Los fantasmas mas queridos, Gastly ,Haunter y Gengar", precio: 7000, talle: "L", img: './img/camisa.jpg'},
    {id: 16, nombre: "Camisa de Pueblo Lavanda", tipo: "camisa", cantidad: 1, desc: "Los fantasmas mas queridos, Gastly ,Haunter y Gengar", precio: 777, talle: "S", img: './img/camisa.jpg'},
    {id: 17, nombre: "Camisa de Pueblo Lavanda", tipo: "camisa", cantidad: 1, desc: "Los fantasmas mas queridos, Gastly ,Haunter y Gengar", precio: 234, talle: "S", img: './img/camisa.jpg'},
    {id: 18, nombre: "Camisa de Pueblo Lavanda", tipo: "camisa", cantidad: 1, desc: "Los fantasmas mas queridos, Gastly ,Haunter y Gengar", precio: 155600, talle: "M", img: './img/camisa.jpg'},
    {id: 19, nombre: "Jogging", tipo: "pantalon", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1600, talle: "L", img: './img/pantalon.jpg'},
    {id: 20, nombre: "Pantalon 2", tipo: "pantalon", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 3200, talle: "L", img: './img/pantalon.jpg'},
    {id: 21, nombre: "Pantalon 3", tipo: "pantalon", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 2300, talle: "M", img: './img/pantalon.jpg'},
    {id: 22, nombre: "Pantalon 4", tipo: "pantalon", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 5600, talle: "M", img: './img/pantalon.jpg'},
    {id: 23, nombre: "Pantalon 5", tipo: "pantalon", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: './img/pantalon.jpg'},
    {id: 24, nombre: "Pantalon 6", tipo: "pantalon", cantidad: 1, desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: './img/pantalon.jpg'},
]